#!/bin/bash

# Local Development Setup Script
# This script sets up the application for local testing

set -e

echo "🚀 Setting up MoH Uganda IMS for local development..."
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

# Check if running as postgres user or if we can access PostgreSQL
if [ "$USER" = "postgres" ]; then
    POSTGRES_USER=""
    SUDO_CMD=""
elif sudo -n true 2>/dev/null; then
    POSTGRES_USER="sudo -u postgres"
    SUDO_CMD="sudo"
else
    echo -e "${YELLOW}⚠️  Note: You may need to run database setup commands manually${NC}"
    echo "   Or run this script with sudo for database setup"
    POSTGRES_USER=""
    SUDO_CMD=""
fi

# Step 1: Generate development secrets
echo -e "${BLUE}Step 1: Generating development secrets...${NC}"
if command -v node &> /dev/null; then
    DEV_JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
    DEV_DB_PASSWORD=$(node -e "console.log(require('crypto').randomBytes(16).toString('base64'))")
else
    DEV_JWT_SECRET=$(openssl rand -hex 32)
    DEV_DB_PASSWORD=$(openssl rand -base64 16)
fi

echo -e "${GREEN}✅ Secrets generated${NC}"
echo ""

# Step 2: Set up database
echo -e "${BLUE}Step 2: Setting up PostgreSQL database...${NC}"

# Check if database exists
DB_EXISTS=$($POSTGRES_USER psql -tAc "SELECT 1 FROM pg_database WHERE datname='inventory_db'" 2>/dev/null || echo "0")

if [ "$DB_EXISTS" = "1" ]; then
    echo -e "${YELLOW}⚠️  Database 'inventory_db' already exists${NC}"
    read -p "Do you want to recreate it? (y/N): " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        $POSTGRES_USER psql -c "DROP DATABASE IF EXISTS inventory_db;" 2>/dev/null || true
        $POSTGRES_USER psql -c "DROP USER IF EXISTS inventory_user;" 2>/dev/null || true
        DB_EXISTS="0"
    fi
fi

if [ "$DB_EXISTS" != "1" ]; then
    echo "Creating database and user..."
    
    # Create database
    $POSTGRES_USER psql -c "CREATE DATABASE inventory_db;" 2>/dev/null || {
        echo -e "${RED}❌ Failed to create database. You may need to run:${NC}"
        echo "   sudo -u postgres psql -c \"CREATE DATABASE inventory_db;\""
        echo "   sudo -u postgres psql -c \"CREATE USER inventory_user WITH PASSWORD '$DEV_DB_PASSWORD';\""
        echo "   sudo -u postgres psql -c \"GRANT ALL PRIVILEGES ON DATABASE inventory_db TO inventory_user;\""
        exit 1
    }
    
    # Create user
    $POSTGRES_USER psql -c "CREATE USER inventory_user WITH PASSWORD '$DEV_DB_PASSWORD';" 2>/dev/null || {
        echo -e "${YELLOW}⚠️  User may already exist, continuing...${NC}"
    }
    
    # Grant privileges
    $POSTGRES_USER psql -c "GRANT ALL PRIVILEGES ON DATABASE inventory_db TO inventory_user;" 2>/dev/null || true
    $POSTGRES_USER psql -c "ALTER USER inventory_user CREATEDB;" 2>/dev/null || true
    
    echo -e "${GREEN}✅ Database and user created${NC}"
else
    echo -e "${GREEN}✅ Database already exists${NC}"
fi

echo ""

# Step 3: Update backend environment file
echo -e "${BLUE}Step 3: Configuring backend environment...${NC}"

BACKEND_ENV="config/environments/backend.env"

# Backup existing file if it has real values
if [ -f "$BACKEND_ENV" ] && ! grep -q "CHANGE_THIS" "$BACKEND_ENV"; then
    cp "$BACKEND_ENV" "$BACKEND_ENV.backup.$(date +%Y%m%d_%H%M%S)"
    echo -e "${YELLOW}⚠️  Backed up existing backend.env${NC}"
fi

# Update backend.env
cat > "$BACKEND_ENV" << EOF
# Ministry of Health Uganda Inventory Management System
# Environment Configuration - Local Development
# Generated by setup-local-dev.sh on $(date)

# Server Configuration
PORT=5000
NODE_ENV=development

# Database Configuration (PostgreSQL)
DB_HOST=localhost
DB_PORT=5432
DB_NAME=inventory_db
DB_USER=inventory_user
DB_PASS=$DEV_DB_PASSWORD

# JWT Configuration
SECRETKEY=$DEV_JWT_SECRET
JWT_SECRET=$DEV_JWT_SECRET
JWT_EXPIRE=30d

# Email Configuration (Optional - not required for local dev)
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_USER=your_email@gmail.com
EMAIL_PASS=your_app_password

# File Upload Configuration
MAX_FILE_SIZE=10000000
UPLOAD_PATH=./uploads

# CORS Configuration
FRONTEND_URL=http://localhost:3000,http://localhost:3001
EOF

echo -e "${GREEN}✅ Backend environment configured${NC}"
echo ""

# Step 4: Install/update dependencies
echo -e "${BLUE}Step 4: Checking dependencies...${NC}"

if [ ! -d "backend/node_modules" ] || [ ! -f "backend/node_modules/.package-lock.json" ]; then
    echo "Installing backend dependencies..."
    cd backend && npm install && cd ..
    echo -e "${GREEN}✅ Backend dependencies installed${NC}"
else
    echo -e "${GREEN}✅ Backend dependencies already installed${NC}"
fi

if [ ! -d "frontend/node_modules" ] || [ ! -f "frontend/node_modules/.package-lock.json" ]; then
    echo "Installing frontend dependencies..."
    cd frontend && npm install && cd ..
    echo -e "${GREEN}✅ Frontend dependencies installed${NC}"
else
    echo -e "${GREEN}✅ Frontend dependencies already installed${NC}"
fi

echo ""

# Step 5: Create necessary directories
echo -e "${BLUE}Step 5: Creating necessary directories...${NC}"
mkdir -p backend/uploads
mkdir -p logs
chmod 755 backend/uploads
echo -e "${GREEN}✅ Directories created${NC}"
echo ""

# Step 6: Run database migrations
echo -e "${BLUE}Step 6: Running database migrations...${NC}"
cd backend

# Check if sequelize-cli is available
if [ -f "node_modules/.bin/sequelize-cli" ] || [ -f "../node_modules/.bin/sequelize-cli" ]; then
    echo "Running migrations..."
    npx sequelize-cli db:migrate 2>/dev/null || {
        echo -e "${YELLOW}⚠️  Migrations may have already run or need manual execution${NC}"
        echo "   You can run manually: cd backend && npx sequelize-cli db:migrate"
    }
    echo -e "${GREEN}✅ Migrations completed${NC}"
else
    echo -e "${YELLOW}⚠️  Sequelize CLI not found, skipping migrations${NC}"
    echo "   You may need to run migrations manually"
fi

cd ..
echo ""

# Step 7: Summary
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}✅ Setup Complete!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Configuration Summary:"
echo ""
echo "Database:"
echo "  - Name: inventory_db"
echo "  - User: inventory_user"
echo "  - Password: $DEV_DB_PASSWORD"
echo ""
echo "Backend:"
echo "  - Port: 5000"
echo "  - Environment: development"
echo "  - Config: config/environments/backend.env"
echo ""
echo "Frontend:"
echo "  - Port: 3000 (dev server) or 3001"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 Next Steps:"
echo ""
echo "1. Start the backend server:"
echo "   cd backend && npm start"
echo ""
echo "2. Start the frontend server (in another terminal):"
echo "   cd frontend && npm start"
echo ""
echo "3. Access the application:"
echo "   Frontend: http://localhost:3000"
echo "   Backend API: http://localhost:5000"
echo ""
echo "4. Default login credentials (change after first login):"
echo "   Username: admin"
echo "   Password: admin123"
echo ""
echo -e "${YELLOW}⚠️  Remember to change default passwords after first login!${NC}"
echo ""























